#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from sys import version_info

if __name__ == "__main__":
    if version_info.major < 3:
        print("python version < 3 is not supported, current version is %s.%s.%s" % (version_info.major, version_info.minor, version_info.micro))
        sys.exit(1)
    from prof_view import ProfileViewer
    ProfileViewer().run()